### ISSUE TITLE
Create-infrastructure step failing due to upload-opsman.sh

### ISSUE THREAD

**Issue by hercules08** [jastev/pcf-pipelines#13]
Thanks for submitting an issue to pcf-pipelines.
Please note that this repository will be officially deprecated soon.

To help us triage the issue, please fill out the following form as much as you can:

## Issue

create-infrastructure step failing stating "pcf-pipelines/install-pcf/azure/tasks/iaas/upload-opsman.sh: line 9: AZURE_IMAGE_SOURCE_REGION: unbound variable"

## Context

Issue occurs after bootstrapping terraforma and attempting to run this command _fly tj -t lite -j install-pcf-azure-pcfcistorage/create-infrastructure_

### Expected result

create-infrastructure step completes successfully.

### Current result

Failing creation of infrastructure

## Steps to Reproduce

Issue this command to fly after bootstrap

## Possible Fix

TBD

## Logs and Screenshots
![image](https://user-images.githubusercontent.com/1912337/46770207-4ee27680-cca3-11e8-888d-d9ec6880353a.png)

**Comment by dtzar** [comment]
fixed by @aheumaier - it was the `set -u` needed to be removed
